name: option_call

on:
  schedule:
    - cron: "15 3 * * 1-5"  
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.11'
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set environment variable
      run: echo "AUTO_MAIL=${{ secrets.AUTO_MAIL }}" >> $GITHUB_ENV
                
    - name: Run main script
      run: |
        python testing_file.py
